# Use the official .NET Core SDK image
FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR /app
EXPOSE 80

# Use the official .NET Core SDK image to build the application
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ["LoyaltySystemAPI/LoyaltySystemAPI.csproj", "LoyaltySystemAPI/"]
RUN dotnet restore "LoyaltySystemAPI/LoyaltySystemAPI.csproj"
COPY . .
WORKDIR "/src/LoyaltySystemAPI"
RUN dotnet build "LoyaltySystemAPI.csproj" -c Release -o /app/build

# Publish the application
FROM build AS publish
RUN dotnet publish "LoyaltySystemAPI.csproj" -c Release -o /app/publish

# Final stage/image
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "LoyaltySystemAPI.dll"]
